// <auto-generated />
namespace FL_FARMACIAS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class initsql : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initsql));
        
        string IMigrationMetadata.Id
        {
            get { return "202410142227489_initsql"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
